const period = (s, e) => [s, e || "Present"].filter(Boolean).join(" → ");

export const MODULES = {
  projects: {
    endpoint: "/projects",
    title: "Your Projects",
    singular: "project",
    icon: "projects",
    tagline: "Proof of work — recruiters look here first.",
    addLabel: "Add project",
    emptyTitle: "SHOW YOUR WORK",
    empty: "Showcase something you built — a class project, hackathon entry, anything real.",
    fields: [
      { name: "title", label: "Title", required: true, placeholder: "Portfolio Pilot" },
      { name: "techStack", label: "Tech stack (comma-separated)", placeholder: "Java, Spring Boot, React" },
      { name: "description", label: "Description", type: "textarea", placeholder: "What it does, your role, the outcome…" },
      { name: "githubUrl", label: "GitHub URL", placeholder: "https://github.com/you/repo" },
      { name: "liveUrl", label: "Live demo URL", placeholder: "https://your-demo.app" },
      { name: "featured", label: "Featured — pin to “Selected work”", type: "checkbox", help: "Featured projects appear first on your public portfolio." },
    ],
    featuredFirst: true,
    dynamicFilter: { key: "tech", label: "Technology", of: (p) => (p.techStack || "").split(",").map((t) => t.trim()).filter(Boolean) },
    titleOf: (p) => p.title,
    subOf: (p) => p.techStack,
    descOf: (p) => p.description,
    metaOf: () => "",
    tagsOf: (p) => (p.techStack || "").split(",").map((t) => t.trim()).filter(Boolean).slice(0, 6),
    linksOf: (p) =>
      [
        p.githubUrl && { label: "GitHub", href: p.githubUrl },
        p.liveUrl && { label: "Live", href: p.liveUrl },
      ].filter(Boolean),
  },
  skills: {
    endpoint: "/skills",
    title: "Professional Skills",
    singular: "skill",
    icon: "skills",
    tagline: "Aim for 5+ skills to max your readiness score.",
    addLabel: "Add skill",
    emptyTitle: "NAME YOUR STACK",
    empty: "List the technologies you can actually use on day one.",
    fields: [
      { name: "name", label: "Skill", required: true, placeholder: "Java" },
      { name: "level", label: "Level", type: "select", required: true, options: ["BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"] },
    ],
    titleOf: (s) => s.name,
    subOf: (s) => s.level,
    descOf: () => "",
    metaOf: () => "",
    tagsOf: (s) => [s.level].filter(Boolean),
    linksOf: () => [],
    filters: [{ key: "level", label: "Level", options: ["BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"], of: (s) => s.level }],
  },
  education: {
    endpoint: "/education",
    title: "Education",
    singular: "entry",
    icon: "education",
    tagline: "Degrees and programs that shaped you.",
    addLabel: "Add education",
    emptyTitle: "YOUR STORY STARTS HERE",
    empty: "Add your education history to complete your professional profile.",
    fields: [
      { name: "school", label: "School", required: true, placeholder: "Anna University" },
      { name: "degree", label: "Degree", required: true, placeholder: "B.E. Computer Science" },
      { name: "fieldOfStudy", label: "Field of study", placeholder: "Computer Science" },
      { name: "startYear", label: "Start year", type: "number", placeholder: "2022" },
      { name: "endYear", label: "End year (blank if studying)", type: "number", placeholder: "2026" },
      { name: "description", label: "Description", type: "textarea", placeholder: "CGPA, relevant coursework…" },
    ],
    titleOf: (e) => e.degree,
    subOf: (e) => e.school,
    descOf: (e) => e.description,
    metaOf: (e) => (e.startYear ? `${e.startYear} → ${e.endYear || "Present"}` : "") + (e.fieldOfStudy ? ` · ${e.fieldOfStudy}` : ""),
    tagsOf: () => [],
    linksOf: () => [],
  },
  experience: {
    endpoint: "/experience",
    title: "Experience",
    singular: "entry",
    icon: "experience",
    tagline: "Internships and jobs — even one entry lifts your score.",
    addLabel: "Add experience",
    emptyTitle: "PROVE YOU'VE SHIPPED",
    empty: "Add an internship, freelance gig, or part-time role.",
    fields: [
      { name: "title", label: "Role", required: true, placeholder: "Web Dev Intern" },
      { name: "company", label: "Company", required: true, placeholder: "Acme Corp" },
      { name: "location", label: "Location", placeholder: "Chennai / Remote" },
      { name: "startPeriod", label: "Start (YYYY-MM)", placeholder: "2024-06" },
      { name: "endPeriod", label: "End (YYYY-MM, blank if current)", placeholder: "2024-12" },
      { name: "description", label: "What you did", type: "textarea", placeholder: "Impact, stack, team…" },
    ],
    titleOf: (e) => e.title,
    subOf: (e) => e.company,
    descOf: (e) => e.description,
    metaOf: (e) => [period(e.startPeriod, e.endPeriod), e.location].filter(Boolean).join(" · "),
    tagsOf: () => [],
    linksOf: () => [],
  },
  certifications: {
    endpoint: "/certifications",
    title: "Certifications",
    singular: "certification",
    icon: "certifications",
    tagline: "Credentials that back up your skills.",
    addLabel: "Add certification",
    emptyTitle: "BACK IT UP",
    empty: "Two certifications max out this section.",
    fields: [
      { name: "name", label: "Name", required: true, placeholder: "AWS Cloud Practitioner" },
      { name: "issuer", label: "Issuer", required: true, placeholder: "Amazon Web Services" },
      { name: "issueDate", label: "Issue date (YYYY-MM)", placeholder: "2025-03" },
      { name: "credentialUrl", label: "Credential URL", placeholder: "https://…" },
    ],
    titleOf: (c) => c.name,
    subOf: (c) => c.issuer,
    descOf: () => "",
    metaOf: (c) => c.issueDate || "",
    tagsOf: () => [],
    linksOf: (c) => (c.credentialUrl ? [{ label: "Verify", href: c.credentialUrl }] : []),
  },
  achievements: {
    endpoint: "/achievements",
    title: "Achievements",
    singular: "achievement",
    icon: "achievements",
    tagline: "Wins, awards, and moments that matter.",
    addLabel: "Add achievement",
    emptyTitle: "OWN YOUR WINS",
    empty: "Hackathons, contests, scholarships — one entry completes this section.",
    fields: [
      { name: "title", label: "Title", required: true, placeholder: "Smart India Hackathon Finalist" },
      { name: "date", label: "Date (YYYY-MM)", placeholder: "2024-12" },
      { name: "description", label: "Description", type: "textarea", placeholder: "What happened, your contribution…" },
      { name: "link", label: "Link", placeholder: "https://…" },
    ],
    titleOf: (a) => a.title,
    subOf: (a) => a.date,
    descOf: (a) => a.description,
    metaOf: () => "",
    tagsOf: () => [],
    linksOf: (a) => (a.link ? [{ label: "View", href: a.link }] : []),
  },
};
